"""
schemas/cdr.py — Pydantic schemas for Call Detail Record.
"""
from datetime import datetime
from pydantic import BaseModel, Field
from app.models.cdr import CallType


class CDRBase(BaseModel):
    caller_number: str = Field(..., max_length=20)
    receiver_number: str = Field(..., max_length=20)
    call_time: datetime
    duration_seconds: int | None = Field(None, ge=0)
    call_type: CallType
    imei_number: str | None = Field(None, max_length=20)
    cell_id: str | None = Field(None, max_length=64)


class CDRCreate(CDRBase):
    """Schema used for creating a CDR row (no id — auto-generated by DB)."""
    pass


class CDRRead(CDRBase):
    """Schema returned in API responses — includes the server-assigned id."""
    id: int

    model_config = {"from_attributes": True}


class CDRSummary(BaseModel):
    """
    Lightweight summary returned by the search endpoint.
    Shows call statistics for a given phone number without returning all rows.
    """
    phone_number: str
    total_calls: int
    total_duration_seconds: int
    first_seen: datetime | None
    last_seen: datetime | None
    unique_contacts: int
    unique_towers: int
